// Code generated by protoc-gen-go. DO NOT EDIT.
// source: daryl.proto

/*
Package daryl is a generated protocol buffer package.

It is generated from these files:
	daryl.proto

It has these top-level messages:
	UserMessageRequest
	UserMessageResponse
	AddHabitRequest
	AddHabitResponse
	StartWorkSessionRequest
	StartWorkSessionResponse
*/
package daryl

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserMessageRequest struct {
	Identifier string `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	Text       string `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
}

func (m *UserMessageRequest) Reset()                    { *m = UserMessageRequest{} }
func (m *UserMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*UserMessageRequest) ProtoMessage()               {}
func (*UserMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserMessageRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *UserMessageRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type UserMessageResponse struct {
}

func (m *UserMessageResponse) Reset()                    { *m = UserMessageResponse{} }
func (m *UserMessageResponse) String() string            { return proto.CompactTextString(m) }
func (*UserMessageResponse) ProtoMessage()               {}
func (*UserMessageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type AddHabitRequest struct {
	Identifier string `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
}

func (m *AddHabitRequest) Reset()                    { *m = AddHabitRequest{} }
func (m *AddHabitRequest) String() string            { return proto.CompactTextString(m) }
func (*AddHabitRequest) ProtoMessage()               {}
func (*AddHabitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddHabitRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

type AddHabitResponse struct {
}

func (m *AddHabitResponse) Reset()                    { *m = AddHabitResponse{} }
func (m *AddHabitResponse) String() string            { return proto.CompactTextString(m) }
func (*AddHabitResponse) ProtoMessage()               {}
func (*AddHabitResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type StartWorkSessionRequest struct {
	Identifier string `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
}

func (m *StartWorkSessionRequest) Reset()                    { *m = StartWorkSessionRequest{} }
func (m *StartWorkSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*StartWorkSessionRequest) ProtoMessage()               {}
func (*StartWorkSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *StartWorkSessionRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

type StartWorkSessionResponse struct {
}

func (m *StartWorkSessionResponse) Reset()                    { *m = StartWorkSessionResponse{} }
func (m *StartWorkSessionResponse) String() string            { return proto.CompactTextString(m) }
func (*StartWorkSessionResponse) ProtoMessage()               {}
func (*StartWorkSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*UserMessageRequest)(nil), "daryl.UserMessageRequest")
	proto.RegisterType((*UserMessageResponse)(nil), "daryl.UserMessageResponse")
	proto.RegisterType((*AddHabitRequest)(nil), "daryl.AddHabitRequest")
	proto.RegisterType((*AddHabitResponse)(nil), "daryl.AddHabitResponse")
	proto.RegisterType((*StartWorkSessionRequest)(nil), "daryl.StartWorkSessionRequest")
	proto.RegisterType((*StartWorkSessionResponse)(nil), "daryl.StartWorkSessionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Daryl service

type DarylClient interface {
	UserMessage(ctx context.Context, in *UserMessageRequest, opts ...grpc.CallOption) (*UserMessageResponse, error)
	AddHabit(ctx context.Context, in *AddHabitRequest, opts ...grpc.CallOption) (*AddHabitResponse, error)
	StartWorkSession(ctx context.Context, in *StartWorkSessionRequest, opts ...grpc.CallOption) (*StartWorkSessionResponse, error)
}

type darylClient struct {
	cc *grpc.ClientConn
}

func NewDarylClient(cc *grpc.ClientConn) DarylClient {
	return &darylClient{cc}
}

func (c *darylClient) UserMessage(ctx context.Context, in *UserMessageRequest, opts ...grpc.CallOption) (*UserMessageResponse, error) {
	out := new(UserMessageResponse)
	err := grpc.Invoke(ctx, "/daryl.Daryl/UserMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *darylClient) AddHabit(ctx context.Context, in *AddHabitRequest, opts ...grpc.CallOption) (*AddHabitResponse, error) {
	out := new(AddHabitResponse)
	err := grpc.Invoke(ctx, "/daryl.Daryl/AddHabit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *darylClient) StartWorkSession(ctx context.Context, in *StartWorkSessionRequest, opts ...grpc.CallOption) (*StartWorkSessionResponse, error) {
	out := new(StartWorkSessionResponse)
	err := grpc.Invoke(ctx, "/daryl.Daryl/StartWorkSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Daryl service

type DarylServer interface {
	UserMessage(context.Context, *UserMessageRequest) (*UserMessageResponse, error)
	AddHabit(context.Context, *AddHabitRequest) (*AddHabitResponse, error)
	StartWorkSession(context.Context, *StartWorkSessionRequest) (*StartWorkSessionResponse, error)
}

func RegisterDarylServer(s *grpc.Server, srv DarylServer) {
	s.RegisterService(&_Daryl_serviceDesc, srv)
}

func _Daryl_UserMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarylServer).UserMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daryl.Daryl/UserMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarylServer).UserMessage(ctx, req.(*UserMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daryl_AddHabit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddHabitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarylServer).AddHabit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daryl.Daryl/AddHabit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarylServer).AddHabit(ctx, req.(*AddHabitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daryl_StartWorkSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWorkSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarylServer).StartWorkSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daryl.Daryl/StartWorkSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarylServer).StartWorkSession(ctx, req.(*StartWorkSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Daryl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "daryl.Daryl",
	HandlerType: (*DarylServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserMessage",
			Handler:    _Daryl_UserMessage_Handler,
		},
		{
			MethodName: "AddHabit",
			Handler:    _Daryl_AddHabit_Handler,
		},
		{
			MethodName: "StartWorkSession",
			Handler:    _Daryl_StartWorkSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "daryl.proto",
}

func init() { proto.RegisterFile("daryl.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x49, 0x2c, 0xaa,
	0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x3c, 0xb8, 0x84, 0x42,
	0x8b, 0x53, 0x8b, 0x7c, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b,
	0x4b, 0x84, 0xe4, 0xb8, 0xb8, 0x32, 0x53, 0x52, 0xf3, 0x4a, 0x32, 0xd3, 0x32, 0x53, 0x8b, 0x24,
	0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x90, 0x44, 0x84, 0x84, 0xb8, 0x58, 0x4a, 0x52, 0x2b, 0x4a,
	0x24, 0x98, 0xc0, 0x32, 0x60, 0xb6, 0x92, 0x28, 0x97, 0x30, 0x8a, 0x49, 0xc5, 0x05, 0xf9, 0x79,
	0xc5, 0xa9, 0x4a, 0x86, 0x5c, 0xfc, 0x8e, 0x29, 0x29, 0x1e, 0x89, 0x49, 0x99, 0x25, 0x44, 0x9a,
	0xae, 0x24, 0xc4, 0x25, 0x80, 0xd0, 0x02, 0x35, 0xc6, 0x92, 0x4b, 0x3c, 0xb8, 0x24, 0xb1, 0xa8,
	0x24, 0x3c, 0xbf, 0x28, 0x3b, 0x38, 0xb5, 0xb8, 0x38, 0x33, 0x3f, 0x8f, 0x58, 0xe3, 0xa4, 0xb8,
	0x24, 0x30, 0xb5, 0x42, 0x8c, 0x35, 0xba, 0xcf, 0xc8, 0xc5, 0xea, 0x02, 0x0a, 0x08, 0x21, 0x17,
	0x2e, 0x6e, 0x24, 0xe7, 0x0b, 0x49, 0xea, 0x41, 0x02, 0x0b, 0x33, 0x70, 0xa4, 0xa4, 0xb0, 0x49,
	0x41, 0xcc, 0x13, 0xb2, 0xe6, 0xe2, 0x80, 0x39, 0x5d, 0x48, 0x0c, 0xaa, 0x0e, 0xcd, 0xfb, 0x52,
	0xe2, 0x18, 0xe2, 0x50, 0xcd, 0xc1, 0x5c, 0x02, 0xe8, 0x0e, 0x15, 0x92, 0x83, 0x2a, 0xc6, 0xe1,
	0x79, 0x29, 0x79, 0x9c, 0xf2, 0x10, 0x43, 0x93, 0xd8, 0xc0, 0xd1, 0x6d, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0xe6, 0xfe, 0xa4, 0xbf, 0xfd, 0x01, 0x00, 0x00,
}
