// Code generated by protoc-gen-go. DO NOT EDIT.
// source: def.proto

/*
Package protodef is a generated protocol buffer package.

It is generated from these files:
	def.proto

It has these top-level messages:
	StartDarylRequest
	HasDarylRequest
	StartDarylResponse
	HasDarylResponse
	Daryl
	UserMessageRequest
	Message
	UserMessageResponse
	Trigger
	Habit
	AddTriggerRequest
	AddTriggerResponse
	AddHabitRequest
	AddHabitResponse
	SessionSlice
	Session
	SessionConfig
	StartWorkSessionRequest
	StartWorkSessionResponse
	CancelWorkSessionRequest
	CancelWorkSessionResponse
	SessionSliceIndex
	RefuseSessionSliceRequest
	RefuseSessionSliceResponse
*/
package protodef

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StartDarylRequest struct {
	Daryl *Daryl `protobuf:"bytes,1,opt,name=daryl" json:"daryl,omitempty"`
}

func (m *StartDarylRequest) Reset()                    { *m = StartDarylRequest{} }
func (m *StartDarylRequest) String() string            { return proto.CompactTextString(m) }
func (*StartDarylRequest) ProtoMessage()               {}
func (*StartDarylRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StartDarylRequest) GetDaryl() *Daryl {
	if m != nil {
		return m.Daryl
	}
	return nil
}

type HasDarylRequest struct {
	DarylIdentifier string `protobuf:"bytes,1,opt,name=daryl_identifier,json=darylIdentifier" json:"daryl_identifier,omitempty"`
}

func (m *HasDarylRequest) Reset()                    { *m = HasDarylRequest{} }
func (m *HasDarylRequest) String() string            { return proto.CompactTextString(m) }
func (*HasDarylRequest) ProtoMessage()               {}
func (*HasDarylRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HasDarylRequest) GetDarylIdentifier() string {
	if m != nil {
		return m.DarylIdentifier
	}
	return ""
}

type StartDarylResponse struct {
	Daryl *Daryl `protobuf:"bytes,1,opt,name=daryl" json:"daryl,omitempty"`
}

func (m *StartDarylResponse) Reset()                    { *m = StartDarylResponse{} }
func (m *StartDarylResponse) String() string            { return proto.CompactTextString(m) }
func (*StartDarylResponse) ProtoMessage()               {}
func (*StartDarylResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *StartDarylResponse) GetDaryl() *Daryl {
	if m != nil {
		return m.Daryl
	}
	return nil
}

type HasDarylResponse struct {
	Response bool `protobuf:"varint,1,opt,name=response" json:"response,omitempty"`
}

func (m *HasDarylResponse) Reset()                    { *m = HasDarylResponse{} }
func (m *HasDarylResponse) String() string            { return proto.CompactTextString(m) }
func (*HasDarylResponse) ProtoMessage()               {}
func (*HasDarylResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *HasDarylResponse) GetResponse() bool {
	if m != nil {
		return m.Response
	}
	return false
}

type Daryl struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *Daryl) Reset()                    { *m = Daryl{} }
func (m *Daryl) String() string            { return proto.CompactTextString(m) }
func (*Daryl) ProtoMessage()               {}
func (*Daryl) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Daryl) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Daryl) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Daryl) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserMessageRequest struct {
	DarylIdentifier string   `protobuf:"bytes,1,opt,name=daryl_identifier,json=darylIdentifier" json:"daryl_identifier,omitempty"`
	Message         *Message `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *UserMessageRequest) Reset()                    { *m = UserMessageRequest{} }
func (m *UserMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*UserMessageRequest) ProtoMessage()               {}
func (*UserMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UserMessageRequest) GetDarylIdentifier() string {
	if m != nil {
		return m.DarylIdentifier
	}
	return ""
}

func (m *UserMessageRequest) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type Message struct {
	Id              string                     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Text            string                     `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	HabitIdentifier string                     `protobuf:"bytes,3,opt,name=habit_identifier,json=habitIdentifier" json:"habit_identifier,omitempty"`
	At              *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=at" json:"at,omitempty"`
	Attrs           []byte                     `protobuf:"bytes,5,opt,name=attrs,proto3" json:"attrs,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Message) GetHabitIdentifier() string {
	if m != nil {
		return m.HabitIdentifier
	}
	return ""
}

func (m *Message) GetAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.At
	}
	return nil
}

func (m *Message) GetAttrs() []byte {
	if m != nil {
		return m.Attrs
	}
	return nil
}

type UserMessageResponse struct {
	Message *Message `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *UserMessageResponse) Reset()                    { *m = UserMessageResponse{} }
func (m *UserMessageResponse) String() string            { return proto.CompactTextString(m) }
func (*UserMessageResponse) ProtoMessage()               {}
func (*UserMessageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UserMessageResponse) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type Trigger struct {
	Id              string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	HabitIdentifier string `protobuf:"bytes,2,opt,name=habit_identifier,json=habitIdentifier" json:"habit_identifier,omitempty"`
	Name            string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Engine          string `protobuf:"bytes,4,opt,name=engine" json:"engine,omitempty"`
	Params          []byte `protobuf:"bytes,5,opt,name=params,proto3" json:"params,omitempty"`
}

func (m *Trigger) Reset()                    { *m = Trigger{} }
func (m *Trigger) String() string            { return proto.CompactTextString(m) }
func (*Trigger) ProtoMessage()               {}
func (*Trigger) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Trigger) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Trigger) GetHabitIdentifier() string {
	if m != nil {
		return m.HabitIdentifier
	}
	return ""
}

func (m *Trigger) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Trigger) GetEngine() string {
	if m != nil {
		return m.Engine
	}
	return ""
}

func (m *Trigger) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

type Habit struct {
	Id       string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title    string     `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Duration string     `protobuf:"bytes,3,opt,name=duration" json:"duration,omitempty"`
	Triggers []*Trigger `protobuf:"bytes,4,rep,name=triggers" json:"triggers,omitempty"`
}

func (m *Habit) Reset()                    { *m = Habit{} }
func (m *Habit) String() string            { return proto.CompactTextString(m) }
func (*Habit) ProtoMessage()               {}
func (*Habit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Habit) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Habit) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Habit) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

func (m *Habit) GetTriggers() []*Trigger {
	if m != nil {
		return m.Triggers
	}
	return nil
}

type AddTriggerRequest struct {
	DarylIdentifier string   `protobuf:"bytes,1,opt,name=daryl_identifier,json=darylIdentifier" json:"daryl_identifier,omitempty"`
	Trigger         *Trigger `protobuf:"bytes,3,opt,name=trigger" json:"trigger,omitempty"`
}

func (m *AddTriggerRequest) Reset()                    { *m = AddTriggerRequest{} }
func (m *AddTriggerRequest) String() string            { return proto.CompactTextString(m) }
func (*AddTriggerRequest) ProtoMessage()               {}
func (*AddTriggerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *AddTriggerRequest) GetDarylIdentifier() string {
	if m != nil {
		return m.DarylIdentifier
	}
	return ""
}

func (m *AddTriggerRequest) GetTrigger() *Trigger {
	if m != nil {
		return m.Trigger
	}
	return nil
}

type AddTriggerResponse struct {
	Trigger *Trigger `protobuf:"bytes,1,opt,name=trigger" json:"trigger,omitempty"`
}

func (m *AddTriggerResponse) Reset()                    { *m = AddTriggerResponse{} }
func (m *AddTriggerResponse) String() string            { return proto.CompactTextString(m) }
func (*AddTriggerResponse) ProtoMessage()               {}
func (*AddTriggerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *AddTriggerResponse) GetTrigger() *Trigger {
	if m != nil {
		return m.Trigger
	}
	return nil
}

type AddHabitRequest struct {
	DarylIdentifier string `protobuf:"bytes,1,opt,name=daryl_identifier,json=darylIdentifier" json:"daryl_identifier,omitempty"`
	Habit           *Habit `protobuf:"bytes,2,opt,name=habit" json:"habit,omitempty"`
}

func (m *AddHabitRequest) Reset()                    { *m = AddHabitRequest{} }
func (m *AddHabitRequest) String() string            { return proto.CompactTextString(m) }
func (*AddHabitRequest) ProtoMessage()               {}
func (*AddHabitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *AddHabitRequest) GetDarylIdentifier() string {
	if m != nil {
		return m.DarylIdentifier
	}
	return ""
}

func (m *AddHabitRequest) GetHabit() *Habit {
	if m != nil {
		return m.Habit
	}
	return nil
}

type AddHabitResponse struct {
	Habit *Habit `protobuf:"bytes,2,opt,name=habit" json:"habit,omitempty"`
}

func (m *AddHabitResponse) Reset()                    { *m = AddHabitResponse{} }
func (m *AddHabitResponse) String() string            { return proto.CompactTextString(m) }
func (*AddHabitResponse) ProtoMessage()               {}
func (*AddHabitResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *AddHabitResponse) GetHabit() *Habit {
	if m != nil {
		return m.Habit
	}
	return nil
}

type SessionSlice struct {
	Start *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=start" json:"start,omitempty"`
	End   *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=end" json:"end,omitempty"`
	Habit *Habit                     `protobuf:"bytes,3,opt,name=habit" json:"habit,omitempty"`
}

func (m *SessionSlice) Reset()                    { *m = SessionSlice{} }
func (m *SessionSlice) String() string            { return proto.CompactTextString(m) }
func (*SessionSlice) ProtoMessage()               {}
func (*SessionSlice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *SessionSlice) GetStart() *google_protobuf.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *SessionSlice) GetEnd() *google_protobuf.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *SessionSlice) GetHabit() *Habit {
	if m != nil {
		return m.Habit
	}
	return nil
}

type Session struct {
	Start  *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=start" json:"start,omitempty"`
	End    *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=end" json:"end,omitempty"`
	Slices []*SessionSlice            `protobuf:"bytes,3,rep,name=slices" json:"slices,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *Session) GetStart() *google_protobuf.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Session) GetEnd() *google_protobuf.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *Session) GetSlices() []*SessionSlice {
	if m != nil {
		return m.Slices
	}
	return nil
}

type SessionConfig struct {
	Duration string `protobuf:"bytes,1,opt,name=duration" json:"duration,omitempty"`
}

func (m *SessionConfig) Reset()                    { *m = SessionConfig{} }
func (m *SessionConfig) String() string            { return proto.CompactTextString(m) }
func (*SessionConfig) ProtoMessage()               {}
func (*SessionConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *SessionConfig) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

type StartWorkSessionRequest struct {
	DarylIdentifier string         `protobuf:"bytes,1,opt,name=daryl_identifier,json=darylIdentifier" json:"daryl_identifier,omitempty"`
	Config          *SessionConfig `protobuf:"bytes,2,opt,name=config" json:"config,omitempty"`
}

func (m *StartWorkSessionRequest) Reset()                    { *m = StartWorkSessionRequest{} }
func (m *StartWorkSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*StartWorkSessionRequest) ProtoMessage()               {}
func (*StartWorkSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *StartWorkSessionRequest) GetDarylIdentifier() string {
	if m != nil {
		return m.DarylIdentifier
	}
	return ""
}

func (m *StartWorkSessionRequest) GetConfig() *SessionConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type StartWorkSessionResponse struct {
	Session *Session `protobuf:"bytes,2,opt,name=session" json:"session,omitempty"`
}

func (m *StartWorkSessionResponse) Reset()                    { *m = StartWorkSessionResponse{} }
func (m *StartWorkSessionResponse) String() string            { return proto.CompactTextString(m) }
func (*StartWorkSessionResponse) ProtoMessage()               {}
func (*StartWorkSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *StartWorkSessionResponse) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type CancelWorkSessionRequest struct {
	DarylIdentifier string `protobuf:"bytes,1,opt,name=daryl_identifier,json=darylIdentifier" json:"daryl_identifier,omitempty"`
}

func (m *CancelWorkSessionRequest) Reset()                    { *m = CancelWorkSessionRequest{} }
func (m *CancelWorkSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*CancelWorkSessionRequest) ProtoMessage()               {}
func (*CancelWorkSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *CancelWorkSessionRequest) GetDarylIdentifier() string {
	if m != nil {
		return m.DarylIdentifier
	}
	return ""
}

type CancelWorkSessionResponse struct {
}

func (m *CancelWorkSessionResponse) Reset()                    { *m = CancelWorkSessionResponse{} }
func (m *CancelWorkSessionResponse) String() string            { return proto.CompactTextString(m) }
func (*CancelWorkSessionResponse) ProtoMessage()               {}
func (*CancelWorkSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type SessionSliceIndex struct {
	Index uint32 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
}

func (m *SessionSliceIndex) Reset()                    { *m = SessionSliceIndex{} }
func (m *SessionSliceIndex) String() string            { return proto.CompactTextString(m) }
func (*SessionSliceIndex) ProtoMessage()               {}
func (*SessionSliceIndex) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *SessionSliceIndex) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type RefuseSessionSliceRequest struct {
	DarylIdentifier string             `protobuf:"bytes,1,opt,name=daryl_identifier,json=darylIdentifier" json:"daryl_identifier,omitempty"`
	Index           *SessionSliceIndex `protobuf:"bytes,2,opt,name=index" json:"index,omitempty"`
}

func (m *RefuseSessionSliceRequest) Reset()                    { *m = RefuseSessionSliceRequest{} }
func (m *RefuseSessionSliceRequest) String() string            { return proto.CompactTextString(m) }
func (*RefuseSessionSliceRequest) ProtoMessage()               {}
func (*RefuseSessionSliceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *RefuseSessionSliceRequest) GetDarylIdentifier() string {
	if m != nil {
		return m.DarylIdentifier
	}
	return ""
}

func (m *RefuseSessionSliceRequest) GetIndex() *SessionSliceIndex {
	if m != nil {
		return m.Index
	}
	return nil
}

type RefuseSessionSliceResponse struct {
}

func (m *RefuseSessionSliceResponse) Reset()                    { *m = RefuseSessionSliceResponse{} }
func (m *RefuseSessionSliceResponse) String() string            { return proto.CompactTextString(m) }
func (*RefuseSessionSliceResponse) ProtoMessage()               {}
func (*RefuseSessionSliceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func init() {
	proto.RegisterType((*StartDarylRequest)(nil), "protodef.StartDarylRequest")
	proto.RegisterType((*HasDarylRequest)(nil), "protodef.HasDarylRequest")
	proto.RegisterType((*StartDarylResponse)(nil), "protodef.StartDarylResponse")
	proto.RegisterType((*HasDarylResponse)(nil), "protodef.HasDarylResponse")
	proto.RegisterType((*Daryl)(nil), "protodef.Daryl")
	proto.RegisterType((*UserMessageRequest)(nil), "protodef.UserMessageRequest")
	proto.RegisterType((*Message)(nil), "protodef.Message")
	proto.RegisterType((*UserMessageResponse)(nil), "protodef.UserMessageResponse")
	proto.RegisterType((*Trigger)(nil), "protodef.Trigger")
	proto.RegisterType((*Habit)(nil), "protodef.Habit")
	proto.RegisterType((*AddTriggerRequest)(nil), "protodef.AddTriggerRequest")
	proto.RegisterType((*AddTriggerResponse)(nil), "protodef.AddTriggerResponse")
	proto.RegisterType((*AddHabitRequest)(nil), "protodef.AddHabitRequest")
	proto.RegisterType((*AddHabitResponse)(nil), "protodef.AddHabitResponse")
	proto.RegisterType((*SessionSlice)(nil), "protodef.SessionSlice")
	proto.RegisterType((*Session)(nil), "protodef.Session")
	proto.RegisterType((*SessionConfig)(nil), "protodef.SessionConfig")
	proto.RegisterType((*StartWorkSessionRequest)(nil), "protodef.StartWorkSessionRequest")
	proto.RegisterType((*StartWorkSessionResponse)(nil), "protodef.StartWorkSessionResponse")
	proto.RegisterType((*CancelWorkSessionRequest)(nil), "protodef.CancelWorkSessionRequest")
	proto.RegisterType((*CancelWorkSessionResponse)(nil), "protodef.CancelWorkSessionResponse")
	proto.RegisterType((*SessionSliceIndex)(nil), "protodef.SessionSliceIndex")
	proto.RegisterType((*RefuseSessionSliceRequest)(nil), "protodef.RefuseSessionSliceRequest")
	proto.RegisterType((*RefuseSessionSliceResponse)(nil), "protodef.RefuseSessionSliceResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FarmService service

type FarmServiceClient interface {
	StartDaryl(ctx context.Context, in *StartDarylRequest, opts ...grpc.CallOption) (*StartDarylResponse, error)
	HasDaryl(ctx context.Context, in *HasDarylRequest, opts ...grpc.CallOption) (*HasDarylResponse, error)
}

type farmServiceClient struct {
	cc *grpc.ClientConn
}

func NewFarmServiceClient(cc *grpc.ClientConn) FarmServiceClient {
	return &farmServiceClient{cc}
}

func (c *farmServiceClient) StartDaryl(ctx context.Context, in *StartDarylRequest, opts ...grpc.CallOption) (*StartDarylResponse, error) {
	out := new(StartDarylResponse)
	err := grpc.Invoke(ctx, "/protodef.FarmService/StartDaryl", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) HasDaryl(ctx context.Context, in *HasDarylRequest, opts ...grpc.CallOption) (*HasDarylResponse, error) {
	out := new(HasDarylResponse)
	err := grpc.Invoke(ctx, "/protodef.FarmService/HasDaryl", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FarmService service

type FarmServiceServer interface {
	StartDaryl(context.Context, *StartDarylRequest) (*StartDarylResponse, error)
	HasDaryl(context.Context, *HasDarylRequest) (*HasDarylResponse, error)
}

func RegisterFarmServiceServer(s *grpc.Server, srv FarmServiceServer) {
	s.RegisterService(&_FarmService_serviceDesc, srv)
}

func _FarmService_StartDaryl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDarylRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).StartDaryl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodef.FarmService/StartDaryl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).StartDaryl(ctx, req.(*StartDarylRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_HasDaryl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasDarylRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).HasDaryl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodef.FarmService/HasDaryl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).HasDaryl(ctx, req.(*HasDarylRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FarmService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protodef.FarmService",
	HandlerType: (*FarmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartDaryl",
			Handler:    _FarmService_StartDaryl_Handler,
		},
		{
			MethodName: "HasDaryl",
			Handler:    _FarmService_HasDaryl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "def.proto",
}

// Client API for DarylService service

type DarylServiceClient interface {
	UserMessage(ctx context.Context, in *UserMessageRequest, opts ...grpc.CallOption) (*UserMessageResponse, error)
	AddHabit(ctx context.Context, in *AddHabitRequest, opts ...grpc.CallOption) (*AddHabitResponse, error)
	AddTrigger(ctx context.Context, in *AddTriggerRequest, opts ...grpc.CallOption) (*AddTriggerResponse, error)
	StartWorkSession(ctx context.Context, in *StartWorkSessionRequest, opts ...grpc.CallOption) (*StartWorkSessionResponse, error)
	CancelWorkSession(ctx context.Context, in *CancelWorkSessionRequest, opts ...grpc.CallOption) (*CancelWorkSessionResponse, error)
	RefuseSessionSlice(ctx context.Context, in *RefuseSessionSliceRequest, opts ...grpc.CallOption) (*RefuseSessionSliceResponse, error)
}

type darylServiceClient struct {
	cc *grpc.ClientConn
}

func NewDarylServiceClient(cc *grpc.ClientConn) DarylServiceClient {
	return &darylServiceClient{cc}
}

func (c *darylServiceClient) UserMessage(ctx context.Context, in *UserMessageRequest, opts ...grpc.CallOption) (*UserMessageResponse, error) {
	out := new(UserMessageResponse)
	err := grpc.Invoke(ctx, "/protodef.DarylService/UserMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *darylServiceClient) AddHabit(ctx context.Context, in *AddHabitRequest, opts ...grpc.CallOption) (*AddHabitResponse, error) {
	out := new(AddHabitResponse)
	err := grpc.Invoke(ctx, "/protodef.DarylService/AddHabit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *darylServiceClient) AddTrigger(ctx context.Context, in *AddTriggerRequest, opts ...grpc.CallOption) (*AddTriggerResponse, error) {
	out := new(AddTriggerResponse)
	err := grpc.Invoke(ctx, "/protodef.DarylService/AddTrigger", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *darylServiceClient) StartWorkSession(ctx context.Context, in *StartWorkSessionRequest, opts ...grpc.CallOption) (*StartWorkSessionResponse, error) {
	out := new(StartWorkSessionResponse)
	err := grpc.Invoke(ctx, "/protodef.DarylService/StartWorkSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *darylServiceClient) CancelWorkSession(ctx context.Context, in *CancelWorkSessionRequest, opts ...grpc.CallOption) (*CancelWorkSessionResponse, error) {
	out := new(CancelWorkSessionResponse)
	err := grpc.Invoke(ctx, "/protodef.DarylService/CancelWorkSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *darylServiceClient) RefuseSessionSlice(ctx context.Context, in *RefuseSessionSliceRequest, opts ...grpc.CallOption) (*RefuseSessionSliceResponse, error) {
	out := new(RefuseSessionSliceResponse)
	err := grpc.Invoke(ctx, "/protodef.DarylService/RefuseSessionSlice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DarylService service

type DarylServiceServer interface {
	UserMessage(context.Context, *UserMessageRequest) (*UserMessageResponse, error)
	AddHabit(context.Context, *AddHabitRequest) (*AddHabitResponse, error)
	AddTrigger(context.Context, *AddTriggerRequest) (*AddTriggerResponse, error)
	StartWorkSession(context.Context, *StartWorkSessionRequest) (*StartWorkSessionResponse, error)
	CancelWorkSession(context.Context, *CancelWorkSessionRequest) (*CancelWorkSessionResponse, error)
	RefuseSessionSlice(context.Context, *RefuseSessionSliceRequest) (*RefuseSessionSliceResponse, error)
}

func RegisterDarylServiceServer(s *grpc.Server, srv DarylServiceServer) {
	s.RegisterService(&_DarylService_serviceDesc, srv)
}

func _DarylService_UserMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarylServiceServer).UserMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodef.DarylService/UserMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarylServiceServer).UserMessage(ctx, req.(*UserMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DarylService_AddHabit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddHabitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarylServiceServer).AddHabit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodef.DarylService/AddHabit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarylServiceServer).AddHabit(ctx, req.(*AddHabitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DarylService_AddTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarylServiceServer).AddTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodef.DarylService/AddTrigger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarylServiceServer).AddTrigger(ctx, req.(*AddTriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DarylService_StartWorkSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWorkSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarylServiceServer).StartWorkSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodef.DarylService/StartWorkSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarylServiceServer).StartWorkSession(ctx, req.(*StartWorkSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DarylService_CancelWorkSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelWorkSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarylServiceServer).CancelWorkSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodef.DarylService/CancelWorkSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarylServiceServer).CancelWorkSession(ctx, req.(*CancelWorkSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DarylService_RefuseSessionSlice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefuseSessionSliceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarylServiceServer).RefuseSessionSlice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodef.DarylService/RefuseSessionSlice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarylServiceServer).RefuseSessionSlice(ctx, req.(*RefuseSessionSliceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DarylService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protodef.DarylService",
	HandlerType: (*DarylServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserMessage",
			Handler:    _DarylService_UserMessage_Handler,
		},
		{
			MethodName: "AddHabit",
			Handler:    _DarylService_AddHabit_Handler,
		},
		{
			MethodName: "AddTrigger",
			Handler:    _DarylService_AddTrigger_Handler,
		},
		{
			MethodName: "StartWorkSession",
			Handler:    _DarylService_StartWorkSession_Handler,
		},
		{
			MethodName: "CancelWorkSession",
			Handler:    _DarylService_CancelWorkSession_Handler,
		},
		{
			MethodName: "RefuseSessionSlice",
			Handler:    _DarylService_RefuseSessionSlice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "def.proto",
}

func init() { proto.RegisterFile("def.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 845 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdf, 0x4f, 0xdb, 0x48,
	0x10, 0x96, 0x93, 0x38, 0x09, 0x13, 0xb8, 0x24, 0x7b, 0x08, 0x8c, 0xe1, 0xa4, 0xdc, 0xde, 0x21,
	0xc1, 0x71, 0x17, 0xee, 0xb8, 0xa7, 0xfb, 0xf1, 0x92, 0xd2, 0x36, 0x50, 0xa9, 0x2f, 0x0e, 0x55,
	0x55, 0xa9, 0x12, 0x5a, 0xe2, 0x4d, 0x6a, 0x91, 0xd8, 0xa9, 0x77, 0xd3, 0xc2, 0x5b, 0x1f, 0xfb,
	0x0f, 0xf4, 0x81, 0xfe, 0xb5, 0x95, 0xf7, 0x47, 0xbc, 0x89, 0x4d, 0x0a, 0x54, 0x7d, 0xca, 0xce,
	0xec, 0xb7, 0x33, 0xdf, 0xcc, 0x7e, 0x9e, 0x0d, 0xac, 0xf8, 0x74, 0xd0, 0x9e, 0xc4, 0x11, 0x8f,
	0x50, 0x55, 0xfc, 0xf8, 0x74, 0xe0, 0xb6, 0x26, 0xfc, 0x7a, 0x42, 0xd9, 0x21, 0x0f, 0xc6, 0x94,
	0x71, 0x32, 0x9e, 0xa4, 0x2b, 0x89, 0xc5, 0xff, 0x42, 0xb3, 0xc7, 0x49, 0xcc, 0x1f, 0x93, 0xf8,
	0x7a, 0xe4, 0xd1, 0xb7, 0x53, 0xca, 0x38, 0xda, 0x05, 0xdb, 0x4f, 0x6c, 0xc7, 0x6a, 0x59, 0x7b,
	0xb5, 0xa3, 0x7a, 0x5b, 0x07, 0x6c, 0x4b, 0x98, 0xdc, 0xc5, 0xff, 0x43, 0xfd, 0x84, 0xb0, 0xb9,
	0x93, 0xfb, 0xd0, 0x10, 0x7b, 0xe7, 0x81, 0x4f, 0x43, 0x1e, 0x0c, 0x02, 0x1a, 0x8b, 0x20, 0x2b,
	0x5e, 0x5d, 0xf8, 0x4f, 0x67, 0x6e, 0xfc, 0x1f, 0x20, 0x33, 0x33, 0x9b, 0x44, 0x21, 0xa3, 0x77,
	0x4d, 0xdd, 0x86, 0x46, 0x9a, 0x5a, 0x1d, 0x75, 0xa1, 0x1a, 0xab, 0xb5, 0x38, 0x5d, 0xf5, 0x66,
	0x36, 0xee, 0x82, 0x2d, 0xc0, 0xe8, 0x07, 0x28, 0x04, 0xbe, 0xa2, 0x54, 0x08, 0x7c, 0x84, 0xa0,
	0x14, 0x92, 0x31, 0x75, 0x0a, 0xc2, 0x23, 0xd6, 0x49, 0xa0, 0x09, 0x61, 0xec, 0x7d, 0x14, 0xfb,
	0x4e, 0x51, 0xf8, 0x67, 0x36, 0x1e, 0x01, 0x7a, 0xc1, 0x68, 0xfc, 0x9c, 0x32, 0x46, 0x86, 0xf4,
	0xfe, 0x65, 0xa3, 0x03, 0xa8, 0x8c, 0xe5, 0x61, 0x91, 0xb3, 0x76, 0xd4, 0x4c, 0x4b, 0xd4, 0x51,
	0x35, 0x02, 0x7f, 0xb6, 0xa0, 0xa2, 0x9c, 0x79, 0xcc, 0x39, 0xbd, 0xe2, 0x9a, 0x79, 0xb2, 0x4e,
	0x78, 0xbc, 0x21, 0x17, 0x01, 0x37, 0x79, 0xc8, 0x0a, 0xea, 0xc2, 0x6f, 0xf0, 0xf8, 0x0d, 0x0a,
	0x84, 0x3b, 0x25, 0x41, 0xc1, 0x6d, 0x0f, 0xa3, 0x68, 0x38, 0xa2, 0x92, 0xc9, 0xc5, 0x74, 0xd0,
	0x3e, 0xd3, 0x32, 0xf1, 0x0a, 0x84, 0xa3, 0x75, 0xb0, 0x09, 0xe7, 0x31, 0x73, 0xec, 0x96, 0xb5,
	0xb7, 0xea, 0x49, 0x03, 0x3f, 0x82, 0x1f, 0xe7, 0x5a, 0xa1, 0xae, 0xe1, 0x5e, 0x05, 0x7e, 0xb4,
	0xa0, 0x72, 0x16, 0x07, 0xc3, 0x21, 0x8d, 0x33, 0x05, 0xe6, 0x15, 0x53, 0xc8, 0x2f, 0x46, 0xdf,
	0x62, 0xd1, 0xb8, 0xc5, 0x0d, 0x28, 0xd3, 0x70, 0x18, 0x84, 0x54, 0x14, 0xb9, 0xe2, 0x29, 0x2b,
	0xf1, 0x4f, 0x48, 0x4c, 0xc6, 0xba, 0x1a, 0x65, 0xe1, 0x2b, 0xb0, 0x4f, 0x92, 0xb0, 0x19, 0x1e,
	0xeb, 0x60, 0xf3, 0x80, 0x8f, 0xb4, 0x46, 0xa4, 0x91, 0x88, 0xc4, 0x9f, 0xc6, 0x84, 0x07, 0x51,
	0xa8, 0x45, 0xa2, 0x6d, 0xf4, 0x07, 0x54, 0xb9, 0x2c, 0x8a, 0x39, 0xa5, 0x56, 0x71, 0xbe, 0x07,
	0xaa, 0x5c, 0x6f, 0x06, 0xc1, 0x97, 0xd0, 0xec, 0xf8, 0xbe, 0xf6, 0x3f, 0x48, 0x52, 0x2a, 0x96,
	0x60, 0x92, 0x9b, 0x4d, 0x23, 0x70, 0x07, 0x90, 0x99, 0x2c, 0xbd, 0x34, 0x1d, 0xc2, 0xfa, 0x6a,
	0x88, 0x3e, 0xd4, 0x3b, 0xbe, 0x2f, 0x9a, 0xf5, 0x00, 0xb6, 0xbb, 0x60, 0x8b, 0xeb, 0x53, 0xea,
	0x30, 0xbe, 0x70, 0x19, 0x51, 0xee, 0xe2, 0x7f, 0xa0, 0x91, 0x26, 0x49, 0x87, 0xc3, 0x5d, 0x8e,
	0x7e, 0xb2, 0x60, 0xb5, 0x47, 0x19, 0x0b, 0xa2, 0xb0, 0x37, 0x0a, 0xfa, 0x14, 0xfd, 0x09, 0x36,
	0x4b, 0x46, 0x8d, 0xaa, 0x6d, 0x99, 0xdc, 0x25, 0x10, 0xfd, 0x0e, 0x45, 0x1a, 0xfa, 0x2a, 0xcf,
	0x32, 0x7c, 0x02, 0x4b, 0x79, 0x15, 0x97, 0xf2, 0xba, 0xb1, 0xa0, 0xa2, 0x78, 0x7d, 0x77, 0x4a,
	0x6d, 0x28, 0xb3, 0xa4, 0x76, 0xe6, 0x14, 0x85, 0x00, 0x37, 0x52, 0x4e, 0x66, 0x6b, 0x3c, 0x85,
	0xc2, 0x07, 0xb0, 0xa6, 0xfc, 0xc7, 0x51, 0x38, 0x08, 0x86, 0x73, 0xfa, 0xb6, 0xe6, 0xf5, 0x8d,
	0xa7, 0xb0, 0x29, 0x46, 0xf7, 0xcb, 0x28, 0xbe, 0x54, 0xa7, 0x1e, 0x20, 0x84, 0x43, 0x28, 0xf7,
	0x45, 0x2e, 0x55, 0xd3, 0x66, 0x86, 0xa2, 0xa4, 0xe2, 0x29, 0x18, 0xee, 0x82, 0x93, 0x4d, 0x9b,
	0x0a, 0x98, 0x49, 0x57, 0x76, 0xea, 0x68, 0xac, 0x46, 0xe0, 0x27, 0xe0, 0x1c, 0x93, 0xb0, 0x4f,
	0x47, 0xdf, 0x54, 0x00, 0xde, 0x86, 0xad, 0x9c, 0x30, 0xea, 0xc5, 0xd9, 0x87, 0xa6, 0xd9, 0xe8,
	0xd3, 0xd0, 0xa7, 0x57, 0xc9, 0x28, 0x09, 0x92, 0x85, 0x88, 0xb8, 0xe6, 0x49, 0x03, 0x5f, 0xc3,
	0x96, 0x47, 0x07, 0x53, 0x46, 0xe7, 0x6e, 0xe6, 0xfe, 0x0d, 0xfd, 0x4b, 0x47, 0x97, 0x1d, 0xd8,
	0xce, 0xbf, 0x72, 0xc1, 0x44, 0xa7, 0xde, 0x01, 0x37, 0x2f, 0xb5, 0xac, 0xe1, 0xe8, 0xc6, 0x82,
	0xda, 0x53, 0x12, 0x8f, 0x7b, 0x34, 0x7e, 0x97, 0x7c, 0x47, 0x5d, 0x80, 0xf4, 0xc9, 0x46, 0x66,
	0xfc, 0xc5, 0xbf, 0x10, 0xee, 0x4e, 0xfe, 0xa6, 0xba, 0xad, 0x0e, 0x54, 0xf5, 0xf3, 0x8d, 0xb6,
	0xcc, 0xaf, 0x65, 0xee, 0xdf, 0x84, 0xeb, 0xe6, 0x6d, 0x29, 0x6e, 0x1f, 0x4a, 0xb0, 0x2a, 0x3c,
	0x9a, 0xdc, 0x33, 0xa8, 0x19, 0xcf, 0x11, 0x32, 0x08, 0x64, 0x1f, 0x6c, 0xf7, 0xa7, 0x5b, 0x76,
	0x53, 0x7e, 0x7a, 0xf8, 0x98, 0xfc, 0x16, 0xa6, 0x9e, 0xc9, 0x2f, 0x33, 0xab, 0xba, 0x00, 0xe9,
	0x9c, 0x35, 0x7b, 0x95, 0x19, 0xf5, 0x66, 0xaf, 0x72, 0x46, 0xf3, 0x2b, 0x68, 0x2c, 0xaa, 0x1e,
	0xfd, 0xbc, 0xd0, 0xdd, 0xac, 0x8e, 0x5d, 0xbc, 0x0c, 0xa2, 0x42, 0xbf, 0x86, 0x66, 0x46, 0xc0,
	0xc8, 0x38, 0x78, 0xdb, 0x47, 0xe2, 0xfe, 0xb2, 0x14, 0xa3, 0xa2, 0x9f, 0x03, 0xca, 0x6a, 0x0b,
	0x19, 0x47, 0x6f, 0x15, 0xbd, 0xfb, 0xeb, 0x72, 0x90, 0x4c, 0x70, 0x51, 0x16, 0xa0, 0xbf, 0xbf,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x76, 0x60, 0x8b, 0x1f, 0xfb, 0x0a, 0x00, 0x00,
}
