// Code generated by protoc-gen-go. DO NOT EDIT.
// source: def.proto

/*
Package protodef is a generated protocol buffer package.

It is generated from these files:
	def.proto

It has these top-level messages:
	StartDarylRequest
	HasDarylRequest
	StatusResponse
	UserMessageRequest
	UserMessageResponse
	Habit
	AddHabitRequest
	AddHabitResponse
	StartWorkSessionRequest
	StartWorkSessionResponse
*/
package protodef

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StartDarylRequest struct {
	Identifier string `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
}

func (m *StartDarylRequest) Reset()                    { *m = StartDarylRequest{} }
func (m *StartDarylRequest) String() string            { return proto.CompactTextString(m) }
func (*StartDarylRequest) ProtoMessage()               {}
func (*StartDarylRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StartDarylRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

type HasDarylRequest struct {
	Identifier string `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
}

func (m *HasDarylRequest) Reset()                    { *m = HasDarylRequest{} }
func (m *HasDarylRequest) String() string            { return proto.CompactTextString(m) }
func (*HasDarylRequest) ProtoMessage()               {}
func (*HasDarylRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HasDarylRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

type StatusResponse struct {
	Ok bool `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
}

func (m *StatusResponse) Reset()                    { *m = StatusResponse{} }
func (m *StatusResponse) String() string            { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()               {}
func (*StatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *StatusResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type UserMessageRequest struct {
	Identifier string `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	Text       string `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
}

func (m *UserMessageRequest) Reset()                    { *m = UserMessageRequest{} }
func (m *UserMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*UserMessageRequest) ProtoMessage()               {}
func (*UserMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserMessageRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *UserMessageRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type UserMessageResponse struct {
}

func (m *UserMessageResponse) Reset()                    { *m = UserMessageResponse{} }
func (m *UserMessageResponse) String() string            { return proto.CompactTextString(m) }
func (*UserMessageResponse) ProtoMessage()               {}
func (*UserMessageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type Habit struct {
	Title       string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	AvgDuration uint32 `protobuf:"varint,2,opt,name=avgDuration" json:"avgDuration,omitempty"`
	Deadline    string `protobuf:"bytes,3,opt,name=deadline" json:"deadline,omitempty"`
	During      uint32 `protobuf:"varint,4,opt,name=during" json:"during,omitempty"`
	Every       uint32 `protobuf:"varint,5,opt,name=every" json:"every,omitempty"`
	EveryUnit   string `protobuf:"bytes,6,opt,name=everyUnit" json:"everyUnit,omitempty"`
}

func (m *Habit) Reset()                    { *m = Habit{} }
func (m *Habit) String() string            { return proto.CompactTextString(m) }
func (*Habit) ProtoMessage()               {}
func (*Habit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Habit) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Habit) GetAvgDuration() uint32 {
	if m != nil {
		return m.AvgDuration
	}
	return 0
}

func (m *Habit) GetDeadline() string {
	if m != nil {
		return m.Deadline
	}
	return ""
}

func (m *Habit) GetDuring() uint32 {
	if m != nil {
		return m.During
	}
	return 0
}

func (m *Habit) GetEvery() uint32 {
	if m != nil {
		return m.Every
	}
	return 0
}

func (m *Habit) GetEveryUnit() string {
	if m != nil {
		return m.EveryUnit
	}
	return ""
}

type AddHabitRequest struct {
	Identifier string `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	Habit      *Habit `protobuf:"bytes,2,opt,name=habit" json:"habit,omitempty"`
}

func (m *AddHabitRequest) Reset()                    { *m = AddHabitRequest{} }
func (m *AddHabitRequest) String() string            { return proto.CompactTextString(m) }
func (*AddHabitRequest) ProtoMessage()               {}
func (*AddHabitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *AddHabitRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *AddHabitRequest) GetHabit() *Habit {
	if m != nil {
		return m.Habit
	}
	return nil
}

type AddHabitResponse struct {
}

func (m *AddHabitResponse) Reset()                    { *m = AddHabitResponse{} }
func (m *AddHabitResponse) String() string            { return proto.CompactTextString(m) }
func (*AddHabitResponse) ProtoMessage()               {}
func (*AddHabitResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type StartWorkSessionRequest struct {
	Identifier string `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
}

func (m *StartWorkSessionRequest) Reset()                    { *m = StartWorkSessionRequest{} }
func (m *StartWorkSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*StartWorkSessionRequest) ProtoMessage()               {}
func (*StartWorkSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *StartWorkSessionRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

type StartWorkSessionResponse struct {
}

func (m *StartWorkSessionResponse) Reset()                    { *m = StartWorkSessionResponse{} }
func (m *StartWorkSessionResponse) String() string            { return proto.CompactTextString(m) }
func (*StartWorkSessionResponse) ProtoMessage()               {}
func (*StartWorkSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func init() {
	proto.RegisterType((*StartDarylRequest)(nil), "protodef.StartDarylRequest")
	proto.RegisterType((*HasDarylRequest)(nil), "protodef.HasDarylRequest")
	proto.RegisterType((*StatusResponse)(nil), "protodef.StatusResponse")
	proto.RegisterType((*UserMessageRequest)(nil), "protodef.UserMessageRequest")
	proto.RegisterType((*UserMessageResponse)(nil), "protodef.UserMessageResponse")
	proto.RegisterType((*Habit)(nil), "protodef.Habit")
	proto.RegisterType((*AddHabitRequest)(nil), "protodef.AddHabitRequest")
	proto.RegisterType((*AddHabitResponse)(nil), "protodef.AddHabitResponse")
	proto.RegisterType((*StartWorkSessionRequest)(nil), "protodef.StartWorkSessionRequest")
	proto.RegisterType((*StartWorkSessionResponse)(nil), "protodef.StartWorkSessionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Farm service

type FarmClient interface {
	StartDaryl(ctx context.Context, in *StartDarylRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	HasDaryl(ctx context.Context, in *HasDarylRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type farmClient struct {
	cc *grpc.ClientConn
}

func NewFarmClient(cc *grpc.ClientConn) FarmClient {
	return &farmClient{cc}
}

func (c *farmClient) StartDaryl(ctx context.Context, in *StartDarylRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := grpc.Invoke(ctx, "/protodef.Farm/StartDaryl", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmClient) HasDaryl(ctx context.Context, in *HasDarylRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := grpc.Invoke(ctx, "/protodef.Farm/HasDaryl", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Farm service

type FarmServer interface {
	StartDaryl(context.Context, *StartDarylRequest) (*StatusResponse, error)
	HasDaryl(context.Context, *HasDarylRequest) (*StatusResponse, error)
}

func RegisterFarmServer(s *grpc.Server, srv FarmServer) {
	s.RegisterService(&_Farm_serviceDesc, srv)
}

func _Farm_StartDaryl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDarylRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServer).StartDaryl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodef.Farm/StartDaryl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServer).StartDaryl(ctx, req.(*StartDarylRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Farm_HasDaryl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasDarylRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServer).HasDaryl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodef.Farm/HasDaryl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServer).HasDaryl(ctx, req.(*HasDarylRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Farm_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protodef.Farm",
	HandlerType: (*FarmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartDaryl",
			Handler:    _Farm_StartDaryl_Handler,
		},
		{
			MethodName: "HasDaryl",
			Handler:    _Farm_HasDaryl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "def.proto",
}

// Client API for Daryl service

type DarylClient interface {
	UserMessage(ctx context.Context, in *UserMessageRequest, opts ...grpc.CallOption) (*UserMessageResponse, error)
	AddHabit(ctx context.Context, in *AddHabitRequest, opts ...grpc.CallOption) (*AddHabitResponse, error)
	StartWorkSession(ctx context.Context, in *StartWorkSessionRequest, opts ...grpc.CallOption) (*StartWorkSessionResponse, error)
}

type darylClient struct {
	cc *grpc.ClientConn
}

func NewDarylClient(cc *grpc.ClientConn) DarylClient {
	return &darylClient{cc}
}

func (c *darylClient) UserMessage(ctx context.Context, in *UserMessageRequest, opts ...grpc.CallOption) (*UserMessageResponse, error) {
	out := new(UserMessageResponse)
	err := grpc.Invoke(ctx, "/protodef.Daryl/UserMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *darylClient) AddHabit(ctx context.Context, in *AddHabitRequest, opts ...grpc.CallOption) (*AddHabitResponse, error) {
	out := new(AddHabitResponse)
	err := grpc.Invoke(ctx, "/protodef.Daryl/AddHabit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *darylClient) StartWorkSession(ctx context.Context, in *StartWorkSessionRequest, opts ...grpc.CallOption) (*StartWorkSessionResponse, error) {
	out := new(StartWorkSessionResponse)
	err := grpc.Invoke(ctx, "/protodef.Daryl/StartWorkSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Daryl service

type DarylServer interface {
	UserMessage(context.Context, *UserMessageRequest) (*UserMessageResponse, error)
	AddHabit(context.Context, *AddHabitRequest) (*AddHabitResponse, error)
	StartWorkSession(context.Context, *StartWorkSessionRequest) (*StartWorkSessionResponse, error)
}

func RegisterDarylServer(s *grpc.Server, srv DarylServer) {
	s.RegisterService(&_Daryl_serviceDesc, srv)
}

func _Daryl_UserMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarylServer).UserMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodef.Daryl/UserMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarylServer).UserMessage(ctx, req.(*UserMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daryl_AddHabit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddHabitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarylServer).AddHabit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodef.Daryl/AddHabit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarylServer).AddHabit(ctx, req.(*AddHabitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daryl_StartWorkSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWorkSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarylServer).StartWorkSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodef.Daryl/StartWorkSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarylServer).StartWorkSession(ctx, req.(*StartWorkSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Daryl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protodef.Daryl",
	HandlerType: (*DarylServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserMessage",
			Handler:    _Daryl_UserMessage_Handler,
		},
		{
			MethodName: "AddHabit",
			Handler:    _Daryl_AddHabit_Handler,
		},
		{
			MethodName: "StartWorkSession",
			Handler:    _Daryl_StartWorkSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "def.proto",
}

func init() { proto.RegisterFile("def.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xdd, 0x8e, 0xd2, 0x40,
	0x14, 0xc7, 0x53, 0xa4, 0xa4, 0x1c, 0xe2, 0xb2, 0x1e, 0xbf, 0xc6, 0xba, 0x1a, 0x9c, 0xc4, 0xc4,
	0x2b, 0x12, 0xd9, 0x2b, 0xaf, 0xcc, 0xc6, 0x8d, 0x21, 0x26, 0xde, 0x94, 0x6c, 0xd4, 0xcb, 0x21,
	0x73, 0xc0, 0x09, 0xd8, 0xc1, 0x99, 0x29, 0x91, 0x77, 0xf0, 0x3d, 0x7c, 0x3e, 0xdf, 0xc0, 0x30,
	0x53, 0x6c, 0xa1, 0x6a, 0xea, 0x15, 0x3d, 0x1f, 0xff, 0xdf, 0x1c, 0xce, 0xf9, 0x43, 0x5f, 0xd2,
	0x62, 0xbc, 0x31, 0xda, 0x69, 0x4c, 0xfc, 0x8f, 0xa4, 0x05, 0xbf, 0x84, 0x3b, 0x33, 0x27, 0x8c,
	0xbb, 0x16, 0x66, 0xb7, 0xce, 0xe8, 0x6b, 0x41, 0xd6, 0xe1, 0x53, 0x00, 0x25, 0x29, 0x77, 0x6a,
	0xa1, 0xc8, 0xb0, 0x68, 0x14, 0xbd, 0xe8, 0x67, 0xb5, 0x0c, 0x7f, 0x09, 0xc3, 0xa9, 0xb0, 0xff,
	0x25, 0x19, 0xc1, 0xd9, 0xcc, 0x09, 0x57, 0xd8, 0x8c, 0xec, 0x46, 0xe7, 0x96, 0xf0, 0x0c, 0x3a,
	0x7a, 0xe5, 0x3b, 0x93, 0xac, 0xa3, 0x57, 0x7c, 0x0a, 0x78, 0x63, 0xc9, 0xbc, 0x27, 0x6b, 0xc5,
	0x92, 0x5a, 0x72, 0x11, 0xa1, 0xeb, 0xe8, 0x9b, 0x63, 0x1d, 0x5f, 0xf1, 0xdf, 0xfc, 0x3e, 0xdc,
	0x3d, 0x22, 0x85, 0x07, 0xf9, 0x8f, 0x08, 0xe2, 0xa9, 0x98, 0x2b, 0x87, 0xf7, 0x20, 0x76, 0xca,
	0xad, 0xa9, 0xe4, 0x85, 0x00, 0x47, 0x30, 0x10, 0xdb, 0xe5, 0x75, 0x61, 0x84, 0x53, 0x3a, 0xf7,
	0xc4, 0xdb, 0x59, 0x3d, 0x85, 0x29, 0x24, 0x92, 0x84, 0x5c, 0xab, 0x9c, 0xd8, 0x2d, 0x2f, 0xfd,
	0x1d, 0xe3, 0x03, 0xe8, 0xc9, 0xc2, 0xa8, 0x7c, 0xc9, 0xba, 0x5e, 0x58, 0x46, 0xfb, 0xb7, 0x68,
	0x4b, 0x66, 0xc7, 0x62, 0x9f, 0x0e, 0x01, 0x5e, 0x40, 0xdf, 0x7f, 0xdc, 0xe4, 0xca, 0xb1, 0x9e,
	0x47, 0x55, 0x09, 0xfe, 0x11, 0x86, 0x57, 0x52, 0xfa, 0x59, 0xdb, 0xee, 0xe1, 0x39, 0xc4, 0x9f,
	0xf7, 0xfd, 0x7e, 0xec, 0xc1, 0x64, 0x38, 0x3e, 0x5c, 0x78, 0x1c, 0x30, 0xa1, 0xca, 0x11, 0xce,
	0x2b, 0x72, 0xb9, 0x97, 0x57, 0xf0, 0xd0, 0x5b, 0xe0, 0x83, 0x36, 0xab, 0x19, 0x59, 0xab, 0x74,
	0xde, 0xf6, 0xaa, 0x29, 0xb0, 0xa6, 0x34, 0x60, 0x27, 0xdf, 0x23, 0xe8, 0xbe, 0x15, 0xe6, 0x0b,
	0xbe, 0x01, 0xa8, 0x2c, 0x86, 0x8f, 0xab, 0xc9, 0x1a, 0xc6, 0x4b, 0xd9, 0x51, 0xb1, 0xee, 0x96,
	0xd7, 0x90, 0x1c, 0x2c, 0x87, 0x8f, 0xea, 0x7f, 0xce, 0xb6, 0x03, 0x4c, 0x7e, 0x46, 0x10, 0x07,
	0xf9, 0x3b, 0x18, 0xd4, 0xec, 0x81, 0x17, 0x95, 0xa4, 0xe9, 0xbf, 0xf4, 0xc9, 0x5f, 0xaa, 0xe5,
	0x58, 0x57, 0x90, 0x1c, 0xf6, 0x59, 0x1f, 0xeb, 0xe4, 0x7a, 0x69, 0xfa, 0xa7, 0x52, 0x89, 0xf8,
	0x04, 0xe7, 0xa7, 0x3b, 0xc4, 0x67, 0x27, 0x4b, 0x6a, 0x9e, 0x26, 0xe5, 0xff, 0x6a, 0x09, 0xe8,
	0x79, 0xcf, 0xb7, 0x5c, 0xfe, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xbc, 0xe1, 0xa4, 0xb7, 0xfa, 0x03,
	0x00, 0x00,
}
